name: Test
on: [push, pull_request]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - name: Compile
      run: sbt compile
    - name: Test
      run: sbt test
